// ðŸŒŸ 13.2.4 More on Promises and Errors

// ðŸŒŸ .catch() to handle Promise-related errors
// ðŸ˜€ .catch() := .then() with null as the first argument and an error-handling callback as the second argument
p = fetch("https://api/user/profile"); // It'll throw an error

// lines 4 and 5 are exactly the same
p.then(null, cb);
p.catch(cb);

function cb(response) {
  console.log("ðŸ”¥");
  console.error(response);
}
