// ðŸŒŸ 13.2.4 More on Promises and Errors

// ðŸŒŸ .finally()
// ðŸ˜€ the callback you pass to .finally() will be certainly invoked when the Promise you called it on settles.

fetch("https://api/user/profile") // It'll throw an error
  .then((res) => {
    console.log(`ðŸ˜€`);
  })
  .catch((res) => {
    console.log(`ðŸ˜…`);
  })
  .finally(() => {
    console.log(`ðŸ˜‡`);
  });
